import { SelectOption } from "shared/ui/Select/Select"

interface allGenresInterface {
	value: string
	content: string
}

export const allGenres: allGenresInterface[] = [
	{ value: "", content: "Любой" },
	{ value: "боевик", content: "Боевик" },
	{ value: "фэнтези", content: "Фэнтези" },
	{ value: "фантастика", content: "Фантастика" },
	{ value: "триллер", content: "Триллер" },
	{ value: "военный", content: "Военный" },
	{ value: "детектив", content: "Детектив" },
	{ value: "комедия", content: "Комедия" },
	{ value: "драма", content: "Драма" },
	{ value: "ужасы", content: "Ужасы" },
	{ value: "криминал", content: "Криминал" },
	{ value: "мелодрама", content: "Мелодрама" },
	{ value: "вестерн", content: "Вестерн" },
	{ value: "биография", content: "Биография" },
	{ value: "аниме", content: "Аниме" },
	{ value: "детский", content: "Детский" },
	{ value: "мультфильм", content: "Мультфильм" },
	{ value: "фильм-нуар", content: "Фильм-нуар" },
	{ value: "для взрослых", content: "Для взрослых" },
	{ value: "документальный", content: "Документальный" },
	{ value: "игра", content: "Игра" },
	{ value: "история", content: "История" },
	{ value: "концерт", content: "Концерт" },
	{ value: "короткометражка", content: "Короткометражка" },
	{ value: "музыка", content: "Музыка" },
	{ value: "мюзикл", content: "Мюзикл" },
	{ value: "новости", content: "Новости" },
	{ value: "приключения", content: "Приключения" },
	{ value: "реальное ТВ", content: "Реальное ТВ" },
	{ value: "семейный", content: "Семейный" },
	{ value: "спорт", content: "Спорт" },
	{ value: "ток-шоу", content: "Ток-шоу" },
	{ value: "церемония", content: "Церемония" },
]

export const ratings: SelectOption<string>[] = [
	{ value: "", content: "Любой рейтинг" },
	{ value: "9-10", content: "Больше 9" },
	{ value: "8-10", content: "Больше 8" },
	{ value: "7-10", content: "Больше 7" },
	{ value: "6-10", content: "Больше 6" },
	{ value: "5-10", content: "Больше 5" },
]

export const years: SelectOption<string>[] = [
	{ value: "", content: "Все годы" },
	{ value: "2022-2023", content: "2022-2023" },
	{ value: "2020-2021", content: "2020-2021" },
	{ value: "2014-2019", content: "2014-2019" },
	{ value: "2010-2014", content: "2010-2014" },
	{ value: "2000-2009", content: "2000-2009" },
	{ value: "1990-1999", content: "1990-1999" },
	{ value: "1980-1989", content: "1980-1989" },
	{ value: "1970-1979", content: "1970-1979" },
	{ value: "1960-1969", content: "1960-1969" },
	{ value: "0-1959", content: "до 1959" },
]

export const allCountries: SelectOption<string>[] = [
	{ value: "", content: "Все страны" },
	{ value: "Австралия", content: "Австралия" },
	{ value: "Австрия", content: "Австрия" },
	{ value: "Азербайджан", content: "Азербайджан" },
	{ value: "Албания", content: "Албания" },
	{ value: "Алжир", content: "Алжир" },
	{ value: "Американские Виргинские острова", content: "Американские Виргинские острова" },
	{ value: "Американское Самоа", content: "Американское Самоа" },
	{ value: "Ангола", content: "Ангола" },
	{ value: "Андорра", content: "Андорра" },
	{ value: "Антарктида", content: "Антарктида" },
	{ value: "Антигуа и Барбуда", content: "Антигуа и Барбуда" },
	{ value: "Антильские Острова", content: "Антильские Острова" },
	{ value: "Аргентина", content: "Аргентина" },
	{ value: "Армения", content: "Армения" },
	{ value: "Аруба", content: "Аруба" },
	{ value: "Афганистан", content: "Афганистан" },
	{ value: "Багамы", content: "Багамы" },
	{ value: "Бангладеш", content: "Бангладеш" },
	{ value: "Барбадос", content: "Барбадос" },
	{ value: "Бахрейн", content: "Бахрейн" },
	{ value: "Беларусь", content: "Беларусь" },
	{ value: "Белиз", content: "Белиз" },
	{ value: "Бельгия", content: "Бельгия" },
	{ value: "Бенин", content: "Бенин" },
	{ value: "Берег Слоновой кости", content: "Берег Слоновой кости" },
	{ value: "Бермуды", content: "Бермуды" },
	{ value: "Бирма", content: "Бирма" },
	{ value: "Болгария", content: "Болгария" },
	{ value: "Боливия", content: "Боливия" },
	{ value: "Босния", content: "Босния" },
	{ value: "Босния и Герцеговина", content: "Босния и Герцеговина" },
	{ value: "Ботсвана", content: "Ботсвана" },
	{ value: "Бразилия", content: "Бразилия" },
	{ value: "Бруней-Даруссалам", content: "Бруней-Даруссалам" },
	{ value: "Буркина-Фасо", content: "Буркина-Фасо" },
	{ value: "Бурунди", content: "Бурунди" },
	{ value: "Бутан", content: "Бутан" },
	{ value: "Вануату", content: "Вануату" },
	{ value: "Ватикан", content: "Ватикан" },
	{ value: "Великобритания", content: "Великобритания" },
	{ value: "Венгрия", content: "Венгрия" },
	{ value: "Венесуэла", content: "Венесуэла" },
	{ value: "Виргинские Острова", content: "Виргинские Острова" },
	{ value: "Внешние малые острова США", content: "Внешние малые острова США" },
	{ value: "Вьетнам", content: "Вьетнам" },
	{ value: "Вьетнам Северный", content: "Вьетнам Северный" },
	{ value: "Габон", content: "Габон" },
	{ value: "Гаити", content: "Гаити" },
	{ value: "Гайана", content: "Гайана" },
	{ value: "Гамбия", content: "Гамбия" },
	{ value: "Гана", content: "Гана" },
	{ value: "Гваделупа", content: "Гваделупа" },
	{ value: "Гватемала", content: "Гватемала" },
	{ value: "Гвинея", content: "Гвинея" },
	{ value: "Гвинея-Бисау", content: "Гвинея-Бисау" },
	{ value: "Германия", content: "Германия" },
	{ value: "Германия (ГДР)", content: "Германия (ГДР)" },
	{ value: "Германия (ФРГ)", content: "Германия (ФРГ)" },
	{ value: "Гибралтар", content: "Гибралтар" },
	{ value: "Гондурас", content: "Гондурас" },
	{ value: "Гонконг", content: "Гонконг" },
	{ value: "Гренада", content: "Гренада" },
	{ value: "Гренландия", content: "Гренландия" },
	{ value: "Греция", content: "Греция" },
	{ value: "Грузия", content: "Грузия" },
	{ value: "Гуам", content: "Гуам" },
	{ value: "Дания", content: "Дания" },
	{ value: "Джибути", content: "Джибути" },
	{ value: "Доминика", content: "Доминика" },
	{ value: "Доминикана", content: "Доминикана" },
	{ value: "Египет", content: "Египет" },
	{ value: "Заир", content: "Заир" },
	{ value: "Замбия", content: "Замбия" },
	{ value: "Западная Сахара", content: "Западная Сахара" },
	{ value: "Зимбабве", content: "Зимбабве" },
	{ value: "Израиль", content: "Израиль" },
	{ value: "Индия", content: "Индия" },
	{ value: "Индонезия", content: "Индонезия" },
	{ value: "Иордания", content: "Иордания" },
	{ value: "Ирак", content: "Ирак" },
	{ value: "Иран", content: "Иран" },
	{ value: "Ирландия", content: "Ирландия" },
	{ value: "Исландия", content: "Исландия" },
	{ value: "Испания", content: "Испания" },
	{ value: "Италия", content: "Италия" },
	{ value: "Йемен", content: "Йемен" },
	{ value: "Кабо-Верде", content: "Кабо-Верде" },
	{ value: "Казахстан", content: "Казахстан" },
	{ value: "Каймановы острова", content: "Каймановы острова" },
	{ value: "Камбоджа", content: "Камбоджа" },
	{ value: "Камерун", content: "Камерун" },
	{ value: "Канада", content: "Канада" },
	{ value: "Катар", content: "Катар" },
	{ value: "Кения", content: "Кения" },
	{ value: "Кипр", content: "Кипр" },
	{ value: "Киргизия", content: "Киргизия" },
	{ value: "Кирибати", content: "Кирибати" },
	{ value: "Китай", content: "Китай" },
	{ value: "Колумбия", content: "Колумбия" },
	{ value: "Коморы", content: "Коморы" },
	{ value: "Конго", content: "Конго" },
	{ value: "Конго (ДРК)", content: "Конго (ДРК)" },
	{ value: "Корея", content: "Корея" },
	{ value: "Корея Северная", content: "Корея Северная" },
	{ value: "Корея Южная", content: "Корея Южная" },
	{ value: "Косово", content: "Косово" },
	{ value: "Коста-Рика", content: "Коста-Рика" },
	{ value: "Кот-д’Ивуар", content: "Кот-д’Ивуар" },
	{ value: "Куба", content: "Куба" },
	{ value: "Кувейт", content: "Кувейт" },
	{ value: "Лаос", content: "Лаос" },
	{ value: "Латвия", content: "Латвия" },
	{ value: "Лесото", content: "Лесото" },
	{ value: "Либерия", content: "Либерия" },
	{ value: "Ливан", content: "Ливан" },
	{ value: "Ливия", content: "Ливия" },
	{ value: "Литва", content: "Литва" },
	{ value: "Лихтенштейн", content: "Лихтенштейн" },
	{ value: "Люксембург", content: "Люксембург" },
	{ value: "Маврикий", content: "Маврикий" },
	{ value: "Мавритания", content: "Мавритания" },
	{ value: "Мадагаскар", content: "Мадагаскар" },
	{ value: "Макао", content: "Макао" },
	{ value: "Македония", content: "Македония" },
	{ value: "Малави", content: "Малави" },
	{ value: "Малайзия", content: "Малайзия" },
	{ value: "Мали", content: "Мали" },
	{ value: "Мальдивы", content: "Мальдивы" },
	{ value: "Мальта", content: "Мальта" },
	{ value: "Марокко", content: "Марокко" },
	{ value: "Мартиника", content: "Мартиника" },
	{ value: "Маршалловы острова", content: "Маршалловы острова" },
	{ value: "Мексика", content: "Мексика" },
	{ value: "Мозамбик", content: "Мозамбик" },
	{ value: "Молдова", content: "Молдова" },
	{ value: "Монако", content: "Монако" },
	{ value: "Монголия", content: "Монголия" },
	{ value: "Монтсеррат", content: "Монтсеррат" },
	{ value: "Мьянма", content: "Мьянма" },
	{ value: "Намибия", content: "Намибия" },
	{ value: "Непал", content: "Непал" },
	{ value: "Нигер", content: "Нигер" },
	{ value: "Нигерия", content: "Нигерия" },
	{ value: "Нидерланды", content: "Нидерланды" },
	{ value: "Никарагуа", content: "Никарагуа" },
	{ value: "Новая Зеландия", content: "Новая Зеландия" },
	{ value: "Новая Каледония", content: "Новая Каледония" },
	{ value: "Норвегия", content: "Норвегия" },
	{ value: "ОАЭ", content: "ОАЭ" },
	{ value: "Оккупированная Палестинская территория", content: "Оккупированная Палестинская территория" },
	{ value: "Оман", content: "Оман" },
	{ value: "Остров Мэн", content: "Остров Мэн" },
	{ value: "Острова Кука", content: "Острова Кука" },
	{ value: "Пакистан", content: "Пакистан" },
	{ value: "Палау", content: "Палау" },
	{ value: "Палестина", content: "Палестина" },
	{ value: "Панама", content: "Панама" },
	{ value: "Папуа - Новая Гвинея", content: "Папуа - Новая Гвинея" },
	{ value: "Парагвай", content: "Парагвай" },
	{ value: "Перу", content: "Перу" },
	{ value: "Польша", content: "Польша" },
	{ value: "Португалия", content: "Португалия" },
	{ value: "Пуэрто Рико", content: "Пуэрто Рико" },
	{ value: "Реюньон", content: "Реюньон" },
	{ value: "Российская империя", content: "Российская империя" },
	{ value: "Россия", content: "Россия" },
	{ value: "Руанда", content: "Руанда" },
	{ value: "Румыния", content: "Румыния" },
	{ value: "СССР", content: "СССР" },
	{ value: "США", content: "США" },
	{ value: "Сальвадор", content: "Сальвадор" },
	{ value: "Самоа", content: "Самоа" },
	{ value: "Сан-Марино", content: "Сан-Марино" },
	{ value: "Саудовская Аравия", content: "Саудовская Аравия" },
	{ value: "Свазиленд", content: "Свазиленд" },
	{ value: "Северная Македония", content: "Северная Македония" },
	{ value: "Сейшельские острова", content: "Сейшельские острова" },
	{ value: "Сенегал", content: "Сенегал" },
	{ value: "Сент-Винсент и Гренадины", content: "Сент-Винсент и Гренадины" },
	{ value: "Сент-Китс и Невис", content: "Сент-Китс и Невис" },
	{ value: "Сент-Люсия ", content: "Сент-Люсия " },
	{ value: "Сербия", content: "Сербия" },
	{ value: "Сербия и Черногория", content: "Сербия и Черногория" },
	{ value: "Сиам", content: "Сиам" },
	{ value: "Сингапур", content: "Сингапур" },
	{ value: "Сирия", content: "Сирия" },
	{ value: "Словакия", content: "Словакия" },
	{ value: "Словения", content: "Словения" },
	{ value: "Соломоновы Острова", content: "Соломоновы Острова" },
	{ value: "Сомали", content: "Сомали" },
	{ value: "Судан", content: "Судан" },
	{ value: "Суринам", content: "Суринам" },
	{ value: "Сьерра-Леоне", content: "Сьерра-Леоне" },
	{ value: "Таджикистан", content: "Таджикистан" },
	{ value: "Таиланд", content: "Таиланд" },
	{ value: "Тайвань", content: "Тайвань" },
	{ value: "Танзания", content: "Танзания" },
	{ value: "Тимор-Лесте", content: "Тимор-Лесте" },
	{ value: "Того", content: "Того" },
	{ value: "Тонга", content: "Тонга" },
	{ value: "Тринидад и Тобаго", content: "Тринидад и Тобаго" },
	{ value: "Тувалу", content: "Тувалу" },
	{ value: "Тунис", content: "Тунис" },
	{ value: "Туркменистан", content: "Туркменистан" },
	{ value: "Турция", content: "Турция" },
	{ value: "Уганда", content: "Уганда" },
	{ value: "Узбекистан", content: "Узбекистан" },
	{ value: "Украина", content: "Украина" },
	{ value: "Уоллис и Футуна", content: "Уоллис и Футуна" },
	{ value: "Уругвай", content: "Уругвай" },
	{ value: "Фарерские острова", content: "Фарерские острова" },
	{ value: "Федеративные Штаты Микронезии", content: "Федеративные Штаты Микронезии" },
	{ value: "Фиджи", content: "Фиджи" },
	{ value: "Филиппины", content: "Филиппины" },
	{ value: "Финляндия", content: "Финляндия" },
	{ value: "Фолклендские острова", content: "Фолклендские острова" },
	{ value: "Франция", content: "Франция" },
	{ value: "Французская Гвиана", content: "Французская Гвиана" },
	{ value: "Французская Полинезия", content: "Французская Полинезия" },
	{ value: "Хорватия", content: "Хорватия" },
	{ value: "ЦАР", content: "ЦАР" },
	{ value: "Чад", content: "Чад" },
	{ value: "Черногория", content: "Черногория" },
	{ value: "Чехия", content: "Чехия" },
	{ value: "Чехословакия", content: "Чехословакия" },
	{ value: "Чили", content: "Чили" },
	{ value: "Швейцария", content: "Швейцария" },
	{ value: "Швеция", content: "Швеция" },
	{ value: "Шри-Ланка", content: "Шри-Ланка" },
	{ value: "Эквадор", content: "Эквадор" },
	{ value: "Экваториальная Гвинея", content: "Экваториальная Гвинея" },
	{ value: "Эритрея", content: "Эритрея" },
	{ value: "Эстония", content: "Эстония" },
	{ value: "Эфиопия", content: "Эфиопия" },
	{ value: "ЮАР", content: "ЮАР" },
	{ value: "Югославия", content: "Югославия" },
	{ value: "Югославия (ФР)", content: "Югославия (ФР)" },
	{ value: "Ямайка", content: "Ямайка" },
	{ value: "Япония", content: "Япония" },
]
