const getAllGenres = {
	boevik: "боевик",
	fentezi: "фэнтези",
	fantastika: "фантастика",
	triller: "триллер",
	voennyj: "военный",
	detektiv: "детектив",
	komediya: "комедия",
	drama: "драма",
	uzhasy: "ужасы",
	kriminal: "криминал",
	melodrama: "мелодрама",
	vestern: "вестерн",
	biografiya: "биография",
	anime: "аниме",
	detskij: "детский",
	multfilm: "мультфильм",
	"film-nuar": "фильм-нуар",
	"dlya-vzroslyh": "для взрослых",
	dokumentalnyj: "документальный",
	igra: "игра",
	istoriya: "история",
	koncert: "концерт",
	korotkometrazhka: "короткометражка",
	muzyka: "музыка",
	myuzikl: "мюзикл",
	novosti: "новости",
	priklyucheniya: "приключения",
	"realnoe-tv": "реальное ТВ",
	semejnyj: "семейный",
	sport: "спорт",
	"tok-shou": "ток-шоу",
	ceremoniya: "церемония",
}

export type allGenresType = keyof typeof getAllGenres

interface allGenresInterface {
	value: allGenresType
	content: string
	disabled: boolean
}

export const allGenres: allGenresInterface[] = [
	{ value: "boevik", content: "Боевик", disabled: false },
	{ value: "fentezi", content: "Фэнтези", disabled: false },
	{ value: "fantastika", content: "Фантастика", disabled: false },
	{ value: "triller", content: "Триллер", disabled: false },
	{ value: "voennyj", content: "Военный", disabled: false },
	{ value: "detektiv", content: "Детектив", disabled: false },
	{ value: "komediya", content: "Комедия", disabled: false },
	{ value: "drama", content: "Драма", disabled: false },
	{ value: "uzhasy", content: "Ужасы", disabled: false },
	{ value: "kriminal", content: "Криминал", disabled: false },
	{ value: "melodrama", content: "Мелодрама", disabled: false },
	{ value: "vestern", content: "Вестерн", disabled: false },
	{ value: "biografiya", content: "Биография", disabled: false },
	{ value: "anime", content: "Аниме", disabled: false },
	{ value: "detskij", content: "Детский", disabled: false },
	{ value: "multfilm", content: "Мультфильм", disabled: false },
	{ value: "film-nuar", content: "Фильм-нуар", disabled: false },
	{ value: "dlya-vzroslyh", content: "Для взрослых", disabled: false },
	{ value: "dokumentalnyj", content: "Документальный", disabled: false },
	{ value: "igra", content: "Игра", disabled: false },
	{ value: "istoriya", content: "История", disabled: false },
	{ value: "koncert", content: "Концерт", disabled: false },
	{ value: "korotkometrazhka", content: "Короткометражка", disabled: false },
	{ value: "muzyka", content: "Музыка", disabled: false },
	{ value: "myuzikl", content: "Мюзикл", disabled: false },
	{ value: "novosti", content: "Новости", disabled: false },
	{ value: "priklyucheniya", content: "Приключения", disabled: false },
	{ value: "realnoe-tv", content: "Реальное ТВ", disabled: false },
	{ value: "semejnyj", content: "Семейный", disabled: false },
	{ value: "sport", content: "Спорт", disabled: false },
	{ value: "tok-shou", content: "Ток-шоу", disabled: false },
	{ value: "ceremoniya", content: "Церемония", disabled: false },
]
