export const getAllGenres = {
	boevik: "боевик",
	fentezi: "фэнтези",
	fantastika: "фантастика",
	triller: "триллер",
	voennyj: "военный",
	detektiv: "детектив",
	komediya: "комедия",
	drama: "драма",
	uzhasy: "ужасы",
	kriminal: "криминал",
	melodrama: "мелодрама",
	vestern: "вестерн",
	biografiya: "биография",
	anime: "аниме",
	detskij: "детский",
	multfilm: "мультфильм",
	"film-nuar": "фильм-нуар",
	"dlya-vzroslyh": "для взрослых",
	dokumentalnyj: "документальный",
	igra: "игра",
	istoriya: "история",
	koncert: "концерт",
	korotkometrazhka: "короткометражка",
	muzyka: "музыка",
	myuzikl: "мюзикл",
	novosti: "новости",
	priklyucheniya: "приключения",
	"realnoe-tv": "реальное ТВ",
	semejnyj: "семейный",
	sport: "спорт",
	"tok-shou": "ток-шоу",
	ceremoniya: "церемония",
}

export const allGenres = [
	{ value: "boevik", content: "боевик", disabled: false },
	{ value: "fentezi", content: "фэнтези", disabled: false },
	{ value: "fantastika", content: "фантастика", disabled: false },
	{ value: "triller", content: "триллер", disabled: false },
	{ value: "voennyj", content: "военный", disabled: false },
	{ value: "detektiv", content: "детектив", disabled: false },
	{ value: "komediya", content: "комедия", disabled: false },
	{ value: "drama", content: "драма", disabled: false },
	{ value: "uzhasy", content: "ужасы", disabled: false },
	{ value: "kriminal", content: "криминал", disabled: false },
	{ value: "melodrama", content: "мелодрама", disabled: false },
	{ value: "vestern", content: "вестерн", disabled: false },
	{ value: "biografiya", content: "биография", disabled: false },
	{ value: "anime", content: "аниме", disabled: false },
	{ value: "detskij", content: "детский", disabled: false },
	{ value: "multfilm", content: "мультфильм", disabled: false },
	{ value: "film-nuar", content: "фильм-нуар", disabled: false },
	{ value: "dlya-vzroslyh", content: "для взрослых", disabled: false },
	{ value: "dokumentalnyj", content: "документальный", disabled: false },
	{ value: "igra", content: "игра", disabled: false },
	{ value: "istoriya", content: "история", disabled: false },
	{ value: "koncert", content: "концерт", disabled: false },
	{ value: "korotkometrazhka", content: "короткометражка", disabled: false },
	{ value: "muzyka", content: "музыка", disabled: false },
	{ value: "myuzikl", content: "мюзикл", disabled: false },
	{ value: "novosti", content: "новости", disabled: false },
	{ value: "priklyucheniya", content: "приключения", disabled: false },
	{ value: "realnoe-tv", content: "реальное ТВ", disabled: false },
	{ value: "semejnyj", content: "семейный", disabled: false },
	{ value: "sport", content: "спорт", disabled: false },
	{ value: "tok-shou", content: "ток-шоу", disabled: false },
	{ value: "ceremoniya", content: "церемония", disabled: false },
]
